apiVersion: apps/v1
kind: Deployment
metadata:
  name: css-dep
  labels:
    env: prod
    app: web
  namespace: prodnamespace
spec:
  minReadySeconds: 6
  replicas: 3
  selector:
    matchLabels:
      app: nginx-css
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-css
      name: nginx-pod
    spec:
      containers:
        - name: nginx-con
          image: rajgandhi123/css-repo:glass 
          ports:
            - containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "500m" 
              memory: "1500Mi"  
            limits:
              cpu: "1800m"        
              memory: "7500Mi" 